"""Report generation and export service."""

import json
import os
import uuid
from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.config import get_settings
from app.models import (
    SimulationRun, ScenarioVersion, Scenario, Report, Citation, Event,
    Driver, Team, ReportFormat, ReportStatus, RunStatus,
)


def _now():
    return datetime.now(timezone.utc)


def _build_markdown(
    simulation_run: SimulationRun,
    scenario_version: ScenarioVersion | None,
    scenario: Scenario | None,
    recommendations: list[dict],
    db: Session,
) -> str:
    """Build a Markdown report."""
    lines = []

    lines.append(f"# F1 Strategic Analysis Report")
    lines.append(f"")
    lines.append(f"**Generated:** {_now().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"")

    if scenario:
        lines.append(f"## Scenario: {scenario.name}")
        lines.append(f"")
        if scenario.goal:
            lines.append(f"**Goal:** {scenario.goal}")
            lines.append(f"")

    if scenario_version:
        lines.append(f"**Version:** {scenario_version.version_number}")
        lines.append(f"")

    numeric = simulation_run.numeric_outputs or {}

    lines.append(f"## Simulation Results")
    lines.append(f"")

    driver_champ = numeric.get("driver_championship_points", {})
    if driver_champ:
        lines.append(f"### Driver Championship Projections")
        lines.append(f"")
        lines.append(f"| Position | Driver | Points |")
        lines.append(f"|----------|--------|--------|")
        drivers = db.query(Driver).filter(Driver.is_deleted == False).all()
        driver_names = {d.id: d.name for d in drivers}
        for i, (did, pts) in enumerate(list(driver_champ.items())[:10], 1):
            name = driver_names.get(did, did[:8])
            lines.append(f"| {i} | {name} | {pts:.1f} |")
        lines.append(f"")

    const_champ = numeric.get("constructor_championship_points", {})
    if const_champ:
        lines.append(f"### Constructor Championship Projections")
        lines.append(f"")
        lines.append(f"| Position | Team | Points |")
        lines.append(f"|----------|------|--------|")
        teams = db.query(Team).filter(Team.is_deleted == False).all()
        team_names = {t.id: t.name for t in teams}
        for i, (tid, pts) in enumerate(list(const_champ.items())[:10], 1):
            name = team_names.get(tid, tid[:8])
            lines.append(f"| {i} | {name} | {pts:.1f} |")
        lines.append(f"")

    dnf = numeric.get("dnf_reliability_probability", {})
    if dnf:
        lines.append(f"### DNF/Reliability Risk")
        lines.append(f"")
        high_risk = {k: v for k, v in dnf.items() if v > 0.08}
        if high_risk:
            for did, prob in sorted(high_risk.items(), key=lambda x: x[1], reverse=True)[:5]:
                name = driver_names.get(did, did[:8])
                lines.append(f"- **{name}**: {prob*100:.1f}% DNF probability")
        lines.append(f"")

    risk_fields = ["political_regulatory_risk", "sponsor_financial_pressure"]
    for field in risk_fields:
        val = numeric.get(field, {})
        if val:
            label = field.replace("_", " ").title()
            lines.append(f"### {label}")
            lines.append(f"- Score: {val.get('score', 'N/A')}")
            lines.append(f"- Confidence: {val.get('confidence', 'N/A')}")
            lines.append(f"")

    explanation = simulation_run.explanation_outputs
    if explanation:
        lines.append(f"## Explanation & Analysis")
        lines.append(f"")
        if isinstance(explanation, list):
            for exp in explanation:
                if isinstance(exp, dict):
                    lines.append(f"- **{exp.get('delta_type', '')}**: {exp.get('description', '')}")
        lines.append(f"")

    if recommendations:
        lines.append(f"## Strategic Recommendations")
        lines.append(f"")
        for rec in recommendations:
            if isinstance(rec, dict):
                lines.append(f"### {rec.get('target_entity', 'Recommendation')}")
                lines.append(f"- **Action:** {rec.get('recommendation', '')}")
                lines.append(f"- **Rationale:** {rec.get('rationale', '')}")
                lines.append(f"- **Confidence:** {rec.get('confidence', '')}")
                lines.append(f"- **Priority:** {rec.get('priority', '')}")
                lines.append(f"")

    lines.append(f"## Citations")
    lines.append(f"")
    citations = db.query(Citation).filter(
        Citation.event_id != None,
    ).limit(20).all()
    for cit in citations:
        lines.append(f"- [{cit.url or 'Source'}] {cit.claim_supported or ''}")
    lines.append(f"")

    lines.append(f"---")
    lines.append(f"*Report generated by F1 Strategic Agentic Analyzer*")
    lines.append(f"*Simulation Run ID: {simulation_run.id}*")

    return "\n".join(lines)


def _build_json_export(
    simulation_run: SimulationRun,
    scenario_version: ScenarioVersion | None,
    recommendations: list[dict],
    db: Session,
) -> dict:
    """Build a JSON export."""
    drivers = db.query(Driver).filter(Driver.is_deleted == False).all()
    teams = db.query(Team).filter(Team.is_deleted == False).all()

    return {
        "generated_at": _now().isoformat(),
        "scenario_version_id": simulation_run.scenario_version_id,
        "simulation_run_id": simulation_run.id,
        "numeric_outputs": simulation_run.numeric_outputs,
        "explanation": simulation_run.explanation_outputs,
        "recommendations": recommendations,
        "entities": {
            "drivers": [{"id": d.id, "name": d.name} for d in drivers],
            "teams": [{"id": t.id, "name": t.name} for t in teams],
        },
    }


def generate_report(
    db: Session,
    simulation_run: SimulationRun,
    report_type: str,
    output_format: str,
) -> Report:
    """Generate a report from a simulation run."""
    settings = get_settings()

    report = Report(
        id=str(uuid.uuid4()),
        report_type=report_type,
        scenario_version_id=simulation_run.scenario_version_id,
        simulation_run_id=simulation_run.id,
        format=ReportFormat(output_format),
        status=ReportStatus("generating"),
    )
    db.add(report)
    db.commit()

    try:
        scenario_version = None
        scenario = None
        if simulation_run.scenario_version_id:
            scenario_version = db.query(ScenarioVersion).filter(
                ScenarioVersion.id == simulation_run.scenario_version_id
            ).first()
            if scenario_version:
                scenario = db.query(Scenario).filter(
                    Scenario.id == scenario_version.scenario_id
                ).first()

        advisory = simulation_run.advisory_outputs or []

        if output_format == "markdown":
            content = _build_markdown(simulation_run, scenario_version, scenario, advisory, db)
            ext = ".md"
            file_content = content.encode("utf-8")
        elif output_format == "json":
            json_data = _build_json_export(simulation_run, scenario_version, advisory, db)
            content = json.dumps(json_data, indent=2, default=str)
            ext = ".json"
            file_content = content.encode("utf-8")
        elif output_format == "pdf":
            md_content = _build_markdown(simulation_run, scenario_version, scenario, advisory, db)
            content = md_content
            ext = ".pdf"
            try:
                from weasyprint import HTML
                import markdown
                html_body = markdown.markdown(md_content, extensions=["tables", "fenced_code"])
                html_doc = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
                <style>body {{ font-family: Arial, sans-serif; max-width: 800px; margin: auto; }}
                table {{ border-collapse: collapse; width: 100%; }} th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
                th {{ background-color: #f2f2f2; }} h1, h2, h3 {{ color: #333; }}</style></head>
                <body>{html_body}</body></html>"""
                file_content = HTML(string=html_doc).write_pdf()
            except Exception:
                report.status = ReportStatus("failed")
                report.failure_details = {"error": "PDF generation requires weasyprint"}
                db.commit()
                return report
        else:
            report.status = ReportStatus("failed")
            report.failure_details = {"error": f"Unsupported format: {output_format}"}
            db.commit()
            return report

        filename = f"report_{simulation_run.id[:8]}_{output_format}{ext}"
        filepath = os.path.join(settings.reports_dir, filename)

        if isinstance(file_content, bytes):
            with open(filepath, "wb") as f:
                f.write(file_content)
        else:
            with open(filepath, "w") as f:
                f.write(file_content)

        report.file_path = filepath
        report.status = ReportStatus("completed")
        report.citation_list = []
        db.commit()
        return report

    except Exception as e:
        report.status = ReportStatus("failed")
        report.failure_details = {"error": str(e)}
        db.commit()
        return report
